services:
  - type: web
    name: backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    plan: free  # Change to a paid plan if required
    rootDir: server

  - type: web
    name: frontend
    env: static
    buildCommand: "npm install && npm run build"
    publishPath: client/dist
    plan: free
    rootDir: client
